version: "{build}"

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1"

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=C:\python27;%PATH%
  - npm install --msvs_version=2013

test_script:
  - node --version
  - npm --version
  - npm test

build: off
